# SITE CONFIGURATION
url: "https://remibou.github.io"
title:  Rémi Bourgarel's Blog # site's title
description: "Blog about software development. Blazor, ASPNET Core, C#, Web Assembly, Spring, Angular, Docker " # used by search engines
name: Rémi Bourgarel's Blog
avatar: https://avatars2.githubusercontent.com/u/1358970?s=40&v=4
# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title:  Rémi Bourgarel's Blog # blog's title
  favicon: assets/favicon.ico
  gravatar: # Email MD5 hash

  # Header and footer text
  header_text: > #two or three lines to describe your site
     <p>Rémi's Blog.</p>
  header_text_feature_image: assets/img/pexels/triangular.jpeg
  footer_text: >
   Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a>

  # Icons
  rss: true  # Make sure you created a feed.xml with feed.xml layout
  email_address: bourgarel.remi@gmail.com
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  gitlab:
  github: "RemiBou"
  google_plus:
  instagram:
  keybase:
  linkedin: https://www.linkedin.com/in/r%C3%A9mi-bourgarel-8092a812/
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  https://stackoverflow.com/users/277067/remi-bourgarel
  steam:
  tumblr:
  twitter: rembou1
  vimeo:
  wordpress:
  youtube:
  
  # Sharing options
  share_buttons:
    facebook: true
    twitter: true
    google_plus: true
    tumblr:
    pinterest:
    pocket:
    reddit: true
    linkedin: true
    wordpress:
    email: true

  # Scripts / Features 
  google_analytics: UA-119823334-1
  disqus_shortname: remibou
  katex: true # Enable if using math markup
  
  special_page:
    search: 
      icon: "search" # Assuming page link and icon are the same
      enabled: true
    tags:
      icon: "tags"
      enabled: true
  
  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_share_on: "Share on"
  str_add_to: "Add to"
  str_email: "Email"
  str_tweet: "Tweet"
  str_pin_it: "Pin it"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true
  
  
# PAGINATION
paginate: 5
paginate_path: "blog/page:num"


# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name


# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag]
#theme: type-on-strap # Uncomment if using the theme as a jekyll theme gem
exclude: ["Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", "LICENSE", "README.md", "screenshot.png", "package.json", "node_modules", "gulpfile.js", ".idea/*"]
